sv is in sbin

diff --git a/bin/sv b/bin/sv
--- a/bin/sv
+++ b/bin/sv
@@ -4,11 +4,11 @@ function main {
   local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
   source "$shome/script/profile"
 
-  local cmd_sv="$(which "$PKG_HOME/install/bin/sv" /usr/local/bin/sv /usr/bin/sv)"
+  local cmd_sv="$(which "$PKG_HOME/install/bin/sv" "$PKG_HOME/install/sbin/sv" /usr/local/bin/sv /usr/bin/sv)"
   if [[ -x "$cmd_sv" ]]; then
     exec "$cmd_sv" "$@"
   else
-    echo "ERROR: runit not found: sv $*" 1>&2
+    echo "ERROR: runit binary not found: sv $*" 1>&2
     false
   fi
 }
